health-check stage modified

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -134,6 +134,9 @@ pipeline {
                     --name rv-constructions \
                     -p 8082:80 \
                     rv-constructions:${BUILD_NUMBER}
+
+                    echo ""
+                    docker ps || true
                 '''
             }
         }
@@ -141,18 +144,26 @@ pipeline {
         stage('Health Check') {
             steps {
                 sh '''
-                    for i in {1..10}
+                    echo "Waiting for application..."
+
+                    for i in {1..15}
                     do
-                        if curl -f http://localhost:8082
+                        if curl -f http://localhost:8082 >/dev/null 2>&1
                         then
+                            echo "Application is UP"
                             exit 0
-                    fi
+                        fi
 
-                    sleep 2
-                done
+                        echo "Retry $i..."
+                        sleep 2
+                    done
 
-                exit 1
-            '''
+                    echo "Application failed to start"
+
+                    docker logs rv-constructions
+
+                    exit 1
+                '''
             }
         }
 
